// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class SignalStreamingGeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new SignalStreamingGeneratedResolver();

        private SignalStreamingGeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = SignalStreamingGeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class SignalStreamingGeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static SignalStreamingGeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8)
            {
                { typeof(global::SignalStreaming.StreamingType), 0 },
                { typeof(global::SignalStreaming.ClientConnectionRequest), 1 },
                { typeof(global::SignalStreaming.ClientConnectionResponse), 2 },
                { typeof(global::SignalStreaming.GroupJoinRequest), 3 },
                { typeof(global::SignalStreaming.GroupJoinResponse), 4 },
                { typeof(global::SignalStreaming.GroupLeaveRequest), 5 },
                { typeof(global::SignalStreaming.GroupLeaveResponse), 6 },
                { typeof(global::SignalStreaming.SendOptions), 7 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new MessagePack.Formatters.SignalStreaming.StreamingTypeFormatter();
                case 1: return new MessagePack.Formatters.SignalStreaming.ClientConnectionRequestFormatter();
                case 2: return new MessagePack.Formatters.SignalStreaming.ClientConnectionResponseFormatter();
                case 3: return new MessagePack.Formatters.SignalStreaming.GroupJoinRequestFormatter();
                case 4: return new MessagePack.Formatters.SignalStreaming.GroupJoinResponseFormatter();
                case 5: return new MessagePack.Formatters.SignalStreaming.GroupLeaveRequestFormatter();
                case 6: return new MessagePack.Formatters.SignalStreaming.GroupLeaveResponseFormatter();
                case 7: return new MessagePack.Formatters.SignalStreaming.SendOptionsFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
